version: "3"

services:
  front:
    container_name: awesomemory-front
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - "4000:3080"

    volumes:
      - type: bind
        source: .
        target: /usr/src/app
      - awesomemory-front-node-modules:/usr/src/app/node_modules

volumes:
  awesomemory-front-node-modules:
